#!/usr/bin/env bash

# Dependencies - webtorrent, mpv

# making cache directories
mkdir -p "$HOME/.cache/flix-cli"
mkdir -p "$HOME/.cache/flix-cli/video"

# some variables
baseurl="https://1337x.to"
cachedir="$HOME/.cache/flix-cli"
videodir="$HOME/.cache/flix-cli/video"

# getting user input
if [ -z "$1" ]; then
  echo "Search:"
  read -r query
else
  query=$1
fi
query="$(echo "$query" | sed 's/ /+/g')"

# doing the scrap
curl -s $baseurl/search/"$query"/1/ > "$cachedir"/tmp.html

# getting titles
grep -o '<a href="/torrent/.*</a>' "$cachedir"/tmp.html |
  sed 's/<[^>]*>//g' > "$cachedir"/titles.bw
result_count=$(wc -l "$cachedir"/titles.bw | awk '{print $1}')

# error message
if [ "$result_count" -lt 1 ]; then
  echo "😔 No Result found. Try again 🔴"
  exit 0
fi

# getting seeders and leechers
grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$cachedir"/tmp.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > "$cachedir"/seedleech.bw

# getting file size
grep -o '<td class="coll-4 size.*</td>' "$cachedir"/tmp.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > "$cachedir"/size.bw

# getting links
grep -E '/torrent/' "$cachedir"/tmp.html |
  sed -E 's#.*(/torrent/.*)/">.*/#\1#' |
  sed 's/td>//g' > "$cachedir"/links.bw

# clearning up some data to display
sed 's/\./ /g; s/\-/ /g' "$cachedir"/titles.bw |
  sed 's/[^A-Za-z0-9 ]//g' | tr -s " " > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/titles.bw

awk '{print NR " - ["$0"]"}' "$cachedir"/size.bw > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/size.bw
awk '{print "[S:"$1 ", L:"$2"]" }' "$cachedir"/seedleech.bw > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/seedleech.bw

# getting the line number
paste -d\  "$cachedir"/size.bw "$cachedir"/titles.bw "$cachedir"/seedleech.bw
echo "Select your stream"
read -r LINE

# error message
if [ -z "$LINE" ]; then
  echo "😔 No Result selected. Exiting... 🔴"
  exit 0
fi

# success message
echo "🔍 Searching Magnet seeds 🧲"
url=$(head -n "$LINE" "$cachedir"/links.bw | tail -n +"$LINE")
fullURL="${baseurl}${url}/"

# requesting page for magnet link
curl -s "$fullURL" > "$cachedir"/tmp.html
magnet=$(grep -Eo "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" "$cachedir"/tmp.html | head -n 1)

# main action
#webtorrent -o "$videodir" "$magnet" --mpv # uncoment if you want to leave everything you watch downloaded on your drive
webtorrent "$magnet" --mpv # comment if you want to use the other option
rm -rf "$cachedir"
exit 0
